name: Publish snapshot to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run tests
      run: ./gradlew test

    - name: Build project
      run: ./gradlew build

    - name: Set snapshot version
      run: |
        VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
        SNAPSHOT_VERSION="${VERSION}-SNAPSHOT"
        sed -i "s/version = \"$VERSION\"/version = \"$SNAPSHOT_VERSION\"/" build.gradle.kts

    - name: Publish snapshot to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}